services:
  keycloakdb:
    image: postgres:latest
    environment:
      #POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: my_admin
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: time_tracker_db
    ports:
      - "5432:5432"
    networks:
      - timetracker-network

  keycloak:
    image: keycloak-ubuntu-test:4
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/time_tracker_db
      KC_DB_USERNAME: my_admin
      KC_DB_PASSWORD: my_password
    ports:
      - "8080:8080"
    networks:
      - timetracker-network
    depends_on:
      - keycloakdb

  postgres:
    container_name: timetrackerdb
    image: postgres:15.1
    environment:
      POSTGRES_DB: timetracker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5431:5432"
    networks:
      - timetracker-network

  pgadmin:
    container_name: pgadmin_op
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: somepass
    networks:
      - timetracker-network
    ports:
      - "5000:80"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    ports:
      - "9200:9200"
    environment:
      - ELASTIC_PASSWORD=dev
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - es-net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
    volumes:
      - kibana-data:/usr/share/kibana/data
    networks:
      - es-net

volumes:
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local

networks:
  es-net:
    driver: bridge
  timetracker-network:
    driver: bridge
